[package]
name = "truthtable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.1"
nom = "7.1.1"
prettytable-rs = "0.9.0"